### PR TITLE
Fix crash on Api 16

### PR DESCRIPTION
**Pull request by dakdroid**
No idea why the model is null here, but this works.
See crashes: http://crashes.to/s/2d2a3d61fb4

### CODE REVIEW

**Comment by michael-rapp** [comment]
Of course adding a null check avoids the NullPointerException from being thrown, but it also prevents the `setPadding`-method from working correctly. So this is just a workaround rather than a proper solution to the underlying problem. Also exceptions might be thrown in other methods that make us of the model. So we have to find out why the model is null in the first place. This should never be the case.

Are you able to reproduce the crash? If yes, can you give instructions how to do so?

**Comment by dakdroid** [comment]
The example does that. run it on an emulator with api 16.

**Comment by michael-rapp** [comment]
Yes, you are right. I was able to reproduce it.

**Comment by michael-rapp** [comment]
It seems like on API level 16 the constructor of the class `FrameLayout` (the one the class `TabSwitcher` extends) or one of its super constructors implicitly calls the `setPadding`-method. At that moment, the model is not yet initialized.

**Comment by michael-rapp** [comment]
I will accept your MR as it is the best thing we can do. The `setPadding`-method is implicity called again during the initialization and therefore therefore the correct values will be set and there are no negative side effects.

 Thank you very much for contributing!

**Comment by michael-rapp** [comment]
The fix is included in version 0.3.2. It may take some time until the new release is available as a  Gradle/Maven dependency.

**Pull request merged**
